### ISSUE TITLE
Status update failure

### ISSUE THREAD

**Issue by jllang763** [f0cker/crackq#10]
After submitting a job, i get `Status update failure` in the logs until I click "Pause/Stop" on the UI. Then it shows completed. 

==Logs===
INFO     root 2020-06-15 17:47:02,050 Registering new job_id to current user: 529fd0c07a4f429fa39fe529376a275f
INFO     root 2020-06-15 17:47:02,053 Adding task to job queue: 529fd0c07a4f429fa39fe529376a275f
INFO     root 2020-06-15 17:47:02,055 API Job 529fd0c07a4f429fa39fe529376a275f added to queue
17:47:02 default: hc_worker(attack_mode=3, brain=True, crack=<crackq.run_hashcat.Crack object at 0x7fc0c11ffe80>, hash_file='/var/crackq/logs/529fd0c07a4f429fa39fe529376a275f.hashes', hash_mode=1000, mask='?2?2?2?2?2?2?2?2?2', mask_file=False, name='TestJob10', outfile='/var/crackq/logs/529fd0c07a4f429fa39fe529376a275f.cracked', pot_path='/var/crackq/logs/crackq.pot', rules=[], session='529fd0c07a4f429fa39fe529376a275f', username=False, wordlist=None) (529fd0c07a4f429fa39fe529376a275f)
INFO     root 2020-06-15 17:47:02,538 Reading from config file /var/crackq/files/crackq.conf
INFO     root 2020-06-15 17:47:02,540 Reading from config file /var/crackq/files/crackq.conf
INFO     root 2020-06-15 17:47:03,060 Reading from config file /var/crackq/files/crackq.conf
INFO     root 2020-06-15 17:47:03,066 Reading from config file /var/crackq/files/crackq.conf
INFO     root 2020-06-15 17:47:03,087 Running hashcat
INFO     root 2020-06-15 17:47:08,093 Running hashcat
WARNING  root 2020-06-15 17:47:34,794 Status update failure
WARNING  root 2020-06-15 17:47:44,804 Status update failure
WARNING  root 2020-06-15 17:47:54,816 Status update failure
WARNING  root 2020-06-15 17:48:04,827 Status update failure
INFO     root 2020-06-15 17:48:09,784 Stopping job: 529fd0c07a4f429fa39fe529376a275f
WARNING  root 2020-06-15 17:48:14,838 Status update failure
INFO     root 2020-06-15 17:48:14,839 Stopping Job: 529fd0c07a4f429fa39fe529376a275f

**Comment by f0cker** [comment]
Thanks for testing this, this is great info. Can you enable debugging please? I think I might have introduced this in one of the latest commits. Are you using the latest from the master branch?

**Comment by f0cker** [comment]
Enable debugging with:
```
sudo docker exec -it crackq /bin/bash
sed -i 's/INFO/DEBUG/g' crackq/log_config.ini
```

**Comment by jllang763** [comment]
Yes, I am on the master branch. The above command does not seem to be giving me debug logs?

**Comment by jllang763** [comment]
I finally got debug turned on. I had to change it in /opt/crackq/build/
Here is the debug log.
[debug-log.txt](https://github.com/f0cker/crackq/files/4782575/debug-log.txt)

**Comment by f0cker** [comment]
Thanks, are there any errors in Job Details when you click that from the GUI? How long was the job initialising before you stopped it? It might not actually be a non issue, I don't think that log needs to be at warning level.

**Comment by jllang763** [comment]
For at least 10 mins. It shows completed after I click stop/pause.

**Comment by jllang763** [comment]
I do not have any errors in the GUI.

**Comment by jllang763** [comment]
So, more testing shows that because those hashes where already crack and are in the .pot file, the job finishes in seconds. I get the 'Status update' error. I am trying a new hash for it to crack and have not gotten the error message.

**Comment by f0cker** [comment]
OK thanks for this, I think I know where to look. I'm in the middle of some big changes in my dev build at the moment, but I'll fix this up as soon as I can.

**Comment by f0cker** [comment]
I've fixed this issue now and will push it with the updates next week.

**Comment by f0cker** [comment]
closing this, let me know if the issue persists in the new branch https://github.com/f0cker/crackq/tree/add_inapp_auth_admin
