### ISSUE TITLE
'notify' error

### ISSUE THREAD

**Issue by jllang763** [f0cker/crackq#11]
After completed a crack job it was placed in "Failed Jobs" with the message of `notify`
![image](https://user-images.githubusercontent.com/51921638/84781332-53008480-afac-11ea-8098-56f13eb59f66.png)

**Comment by f0cker** [comment]
I've fixed this one, I introduced it when adding email notifications. I can't push my updates for a while though as I'm working on adding an admin interface. Should be done by next week.

**Comment by jllang763** [comment]
Even if I had email notifications disabled?

**Comment by f0cker** [comment]
Yeah I think so. Do you have the settings in your config file for notifications? Can you post the debug output and I'll double check.

**Comment by jllang763** [comment]
At the time I did not. Currently, debug is turned off and it is in the middle of a crack job.

**Comment by f0cker** [comment]
OK, I suspect it's looking for the 'notify' section in the config file.

**Comment by jllang763** [comment]
Ok, I added it before the current run. Let's see what happens.

**Comment by jllang763** [comment]
It still failed but this time it had an issue with TLS not being support even when I have that disabled

**Comment by f0cker** [comment]
Can you paste the 'tls' line from the 'notify' section in the config file and also the error and any relevant debug log please? Haven't seen this one before. thanks

**Comment by jllang763** [comment]
[notify]
#Settings for sending out notifications on job status
mail_server: {SMTP-Server}
mail_port: 25
src: {From-Address}
#Time since last user activity to start sending event notifications (email/sms etc.) in minutes
inactive_time: 20
tls: False

**Comment by jllang763** [comment]
I can't find it now but it was trying to use TLS but the server did not support it.

**Comment by f0cker** [comment]
Ah that's a shame I wanted to catch that one as well, it might be a tls/ssl protocol mismatch perhaps. I'll be pushing the updates for the original issue very soon anyway (today/tomorrow). The branch will have an initial version of the admin interface, which I could use some help testing if you want to give it a try.

**Comment by f0cker** [comment]
closing this, let me know if the issue persists in the new branch https://github.com/f0cker/crackq/tree/add_inapp_auth_admin
