### ISSUE TITLE
RuntimeError: Undefined dictionary

### ISSUE THREAD

**Issue by jllang763** [f0cker/crackq#12]
Run the following job
Status: failed
Time started: 2020-06-19 15:50:36.651153
Time finished: 2020-06-19 15:50:36.651680
attack_mode: 1
hash_mode: 1000
mask: None
name: Test
rules: []
username: True
wordlist: rockyou
Result:
email_count: 0
notify: true

=== /var/crackq/files/crackq.conf==
[wordlists]
rockyou: /var/crackq/files/wordlists/skull/rockyou.txt
=========================

==crack.log===
INFO     root 2020-06-19 16:40:41,499 Registering new job_id to current user: 953ece119a95448189eab18458c14ec1
INFO     root 2020-06-19 16:40:41,503 Adding task to job queue: 953ece119a95448189eab18458c14ec1
INFO     root 2020-06-19 16:40:41,504 API Job 953ece119a95448189eab18458c14ec1 added to queue
16:40:41 default: hc_worker(attack_mode=1, brain=True, crack=<crackq.run_hashcat.Crack object at 0x7f80a2adb780>, hash_file='/var/crackq/logs/953ece119a95448189eab18458c14ec1.hashes', hash_mode=1000, mask=None, mask_file=False, name='Test_Comb_01', outfile='/var/crackq/logs/953ece119a95448189eab18458c14ec1.cracked', pot_path='/var/crackq/logs/crackq.pot', rules=[], session='953ece119a95448189eab18458c14ec1', username=True, wordlist='/var/crackq/files/wordlists/skull/rockyou.txt') (953ece119a95448189eab18458c14ec1)
INFO     root 2020-06-19 16:40:41,967 Reading from config file /var/crackq/files/crackq.conf
INFO     root 2020-06-19 16:40:41,969 Reading from config file /var/crackq/files/crackq.conf
INFO     root 2020-06-19 16:40:42,478 Reading from config file /var/crackq/files/crackq.conf
INFO     root 2020-06-19 16:40:42,484 Reading from config file /var/crackq/files/crackq.conf
INFO     root 2020-06-19 16:40:42,504 Running hashcat
16:40:42 Cleaning registries for queue: default
====

bash-4.2$ ls -al /var/crackq/files/wordlists/skull/rockyou.txt
-rw-r--r-- 1 root root 139921497 Mar  5  2018 /var/crackq/files/wordlists/skull/rockyou.txt

**Comment by f0cker** [comment]
Combinator mode requires a second wordlist, and I haven't passed that argument up to the REST API yet. It's a small change, just need to find the time to get around to it.

**Comment by jllang763** [comment]
oh, ok my bad.
