### ISSUE TITLE
Testing without GPU hardware

### ISSUE THREAD

**Issue by jllang763** [f0cker/crackq#14]
I want to do some testing of the "add_inapp_auth_admin" branch but I do not have spare GPU hardware to use. Any suggestions on how to get the crackq docker image running without GPU hardware?

**Comment by f0cker** [comment]
Yeah when you build, you can build it with OpenCL drivers. You just need the OpenCL runtime drivers (https://github.com/intel/compute-runtime/). Then you can use:
sudo ./install.sh docker/opencl/ubuntu or  sudo ./install.sh docker/opencl/centos

Here ubuntu/centos is the OS for the crackq docker container. For my dev env I use the ubuntu build and then docker-compose.dev.yml

Let me know how it goes, I'm going to merge it into master soon. Thanks.
