### ISSUE TITLE
Unknown runtime specified nvidia

### ISSUE THREAD

**Issue by holaloc** [f0cker/crackq#15]
hi,

i tried to install it on fresh Ubuntu 18.04 server but no success 

Successfully built 3f4f6d78db26
Successfully tagged nginx-crackq:latest
Creating redis ... done
Creating crackq ... error

ERROR: for crackq  Cannot create container for service crackq: Unknown runtime specified nvidia

ERROR: for crackq  Cannot create container for service crackq: Unknown runtime specified nvidia
ERROR: Encountered errors while bringing up the project.

**Comment by f0cker** [comment]
Sounds like the nvidia-runtime-toolkit isn't installed properly. Does it show upwhen you run: dpkg -l | grep -i nvidia?

**Comment by holaloc** [comment]
root@pfmon:~/crackq# dpkg -l | grep -i nvidia
ii  libnvidia-container-tools              1.1.1-1                                         amd64        NVIDIA container runtime library (command-line tools)
ii  libnvidia-container1:amd64             1.1.1-1                                         amd64        NVIDIA container runtime library
ii  nvidia-container-toolkit               1.1.2-1                                         amd64        NVIDIA container runtime hook

**Comment by f0cker** [comment]
What versions do you have for docker and docker-compose?

I think you're experiencing this issue:
https://github.com/docker/compose/issues/6691#issuecomment-515741713

Let me know if it works and I'll update the wiki. Thanks.

**Comment by holaloc** [comment]
Same command ? 

sudo docker-compose -f docker-compose.nvidia.yml up --build

**Comment by f0cker** [comment]
Yeah everything the same, but you just need to modify /etc/docker/daemon.json as in the above comment and restart the docker daemon. I haven't tried it because my dev box is not using the latest docker so I don't have this issue, does it work?

**Comment by holaloc** [comment]
Yes working perfectly 👍 

BTW I followed your install wiki so should have latest docker version

**Comment by f0cker** [comment]
Great, I've added a note to the install guide on the wiki and I'll close this off.
