### ISSUE TITLE
Password Input Invalid

### ISSUE THREAD

**Issue by AlexanderKAdams** [f0cker/crackq#26]
What are the restrictions on passwords? I'd generated a password with 1Password which I'll post below (it is now used for nothing and is no longer a secret). I set this password for the initial admin user with the command given in the wiki.
`sudo docker exec -it crackq /usr/bin/python3 /opt/crackq/build/crackq/add_admuser.py`
What about this password makes it invalid, and could that be put somewhere in documentation?
`a1m]@W9J1]q.=gcILp(Q,twI5qj8M@mY`

Error received:
`DEBUG    cq_api.py:580 post 2021-01-26 22:07:32,503 Validation error: {'password': ['Invalid input for this field.']}`

**Comment by f0cker** [comment]
Thanks for reporting, the regex for the password input is below:
(r'[^\w\!\@\#\$\%\^\&\*\(\)\-\+\.\,\\\/]'),

Looks like it's '=' and ']' that are missing from the allowed characters. I can add these in.

**Comment by kernel-sanders** [comment]
A similar issues exists with usernames that contain a `-` character. The frontend is private so I cannot fix and submit a merge request without digging through minified JS.

**Comment by f0cker** [comment]
OK, I'm not planning to update the user field to allow additional characters as I think it's fine as it is. Best to just create a user without the - in this case. Underscores should already be allowed though, it's basically [\W] the regex for that field. I'll have to add in some filtering to the add_admuser.py script to prevent this error in the future. Thanks for reporting.

**Comment by kernel-sanders** [comment]
Would you mind adding me to the fontend repo?

**Comment by f0cker** [comment]
Sure, give me a few days to sort it out. I haven't pushed the latest version there yet.

**Comment by kernel-sanders** [comment]
Friendly bump.

**Comment by f0cker** [comment]
@kernel-sanders do you have a Gitlab.com account? The GUI repo is hosted on there.

**Comment by kernel-sanders** [comment]
https://gitlab.com/kernel-sanders Thanks!

**Comment by f0cker** [comment]
@kernel-sanders All done. Jump on Discord if you have any questions and feel free to submit a PR.

**Comment by f0cker** [comment]
I've pushed the fix to the dev_tasks branch if you want to test it out. I'll merge it in a few weeks
