### ISSUE TITLE
pyhashcat.c:910:16: error: redefinition of 'struct usage_sort'

### ISSUE THREAD

**Issue by Fl4shy** [f0cker/crackq#28]
sudo ./install.sh docker/nvidia/centos

pyhashcat.c:910:16: error: redefinition of 'struct usage_sort'
 typedef struct usage_sort
                ^
In file included from pyhashcat.c:21:0:
hashcat/include/usage.h:12:16: note: originally defined here
 typedef struct usage_sort
                ^
pyhashcat.c:916:3: error: conflicting types for 'usage_sort_t'
 } usage_sort_t;
   ^
In file included from pyhashcat.c:21:0:
hashcat/include/usage.h:18:3: note: previous declaration of 'usage_sort_t' was here
 } usage_sort_t;
   ^
pyhashcat.c:918:12: error: static declaration of 'sort_by_usage' follows non-static declaration
 static int sort_by_usage (const void *p1, const void *p2)
            ^
In file included from pyhashcat.c:21:0:
hashcat/include/usage.h:22:5: note: previous declaration of 'sort_by_usage' was here
 int sort_by_usage (const void *p1, const void *p2);
     ^
error: command 'gcc' failed with exit status 1
running install
running build
running build_ext
building 'pyhashcat' extension
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Ihashcat/include -Ihashcat/deps/OpenCL-Headers -Ihashcat/OpenCL -Ihashcat -Ihashcat/deps/zlib -Ihashcat/deps/LZMA-SDK/C -I/usr/include/python3.6m -c pyhashcat.c -o build/temp.linux-x86_64-3.6/pyhashcat.o -std=c99 -DWITH_BRAIN -Wimplicit-function-declaration
pyhashcat.c:910:16: error: redefinition of 'struct usage_sort'
 typedef struct usage_sort
                ^
In file included from pyhashcat.c:21:0:
hashcat/include/usage.h:12:16: note: originally defined here
 typedef struct usage_sort
                ^
pyhashcat.c:916:3: error: conflicting types for 'usage_sort_t'
 } usage_sort_t;
   ^
In file included from pyhashcat.c:21:0:
hashcat/include/usage.h:18:3: note: previous declaration of 'usage_sort_t' was here
 } usage_sort_t;
   ^
pyhashcat.c:918:12: error: static declaration of 'sort_by_usage' follows non-static declaration
 static int sort_by_usage (const void *p1, const void *p2)
            ^
In file included from pyhashcat.c:21:0:
hashcat/include/usage.h:22:5: note: previous declaration of 'sort_by_usage' was here
 int sort_by_usage (const void *p1, const void *p2);
     ^
error: command 'gcc' failed with exit status 1

**Comment by f0cker** [comment]
This is because of changes in the latest/git version of hashcat. I've pinned it to the latest stable (6.2.2) in the dev_tasks branch. Can you use that branch for now please? I will update pyhashcat to support any newer versions soon, after I've merged all the new features into the master branch.

**Comment by Fl4shy** [comment]
git clone https://github.com/f0cker/crackq.git --branch dev_tasks it working

but a new error
ERROR: for crackq  Cannot create container for service crackq: Unknown runtime specified nvidia

**Comment by f0cker** [comment]
are you following the install guide on the wiki? Sounds like you don't have either the docker-nvidia package installed or the drivers. Look in the troubleshooting page also, I think there's some further help on that error message there

**Comment by f0cker** [comment]
This is fixed in master now. Closing
