### ISSUE TITLE
Only "hundreds of billions of guesses per second"?

### ISSUE THREAD

**Issue by John4589** [f0cker/crackq#4]
Hi,

You guys stated "We're talking hundreds of billions of guesses per second in many cases."
https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/introducing-password-cracking-manager-crackq/

Only that?

For each password, "Multi One Password" tool uses by default a random 248 long characters salt that contains (uppercase\lowercase\digit) characters only and a random 128 long characters salt that contains hex symbols only!

So, here is a quick demonstration on how "hundreds of billions of guesses per second" is really nothing:

999 000 000 000 guesses in 1 second! (999 Billions!)

100000000 seconds = 3.1709791984 years

16^128 (All the 128 possible combinations between the 16 hex symbols!)
62^248 (All the 248 possible combinations between (Uppercase\Lowercase\Digit) chars!)
_____________________________________________________________________________________

999 000 000 000 x 100000000 = below

99 900 000 000 000 000 000 guesses in 3 years!

16^128 = 1.340781e+154 = below 

134078100000000000000000000000000000000000000000000000000000... to be continued!

Even in 3 years you are far far away to guess all the (16^128) possibilities alone!

Well, for (62^248) which is "Infinity" or "Error" in some calculators, I wish you Good Luck!
_____________________________________________________________________________________

By the way, I would like you guys to crack the below hash string generated in "Multi One Password" tool!

58530dfe0bc9c45fc074f56bb05a4d991cc9aa38144774b3014277ae353d7fa0a18aa6b6a33bf7b76ca313c3aa3f8d0e9913e7fcefab3dd3f0461a68a40bb587

The password is 10 characters long and contains only lowercase chars!

(Note) From the demonstration above, it would take you far and far more than 3 years to find the original password!

for aaaaaaaaaa + (16^128 + 62^248) = An Eternity
+
for aaaaaaaaab + (16^128 + 62^248) = An Eternity
+
for aaaaaaaaac + (16^128 + 62^248) = An Eternity
+...
for zzzzzzzzzz + (16^128 + 62^248) = An Eternity

**Comment by roycewilliams** [comment]
This is clearly a poorly-disguised attempt at advertising, similar to what someone (perhaps you?) left here:

https://www.reddit.com/r/sysadmin/comments/dx0c03/multi_one_password/

**Comment by John4589** [comment]
@roycewilliams 

It's just a demonstration on how "hundreds of billions of guesses per second" is really nothing compared with the way "Multi One Password" tool hashes passwords!
