### ISSUE TITLE
Cant start image, flask-login issue

### ISSUE THREAD

**Issue by AlexTryHarder** [f0cker/crackq#41]
**Describe the bug**
Installation seem smooth up to point of starting container, did some digging and seems like flask-login was updated and one of function has been removed? https://stackoverflow.com/questions/77215107/importerror-cannot-import-name-url-decode-from-werkzeug-urls

Error:
`Step 16/16 : CMD ./nginx.sh
 ---> Using cache
 ---> 8b2b8c5d478a

Successfully built 8b2b8c5d478a
Successfully tagged nginx-crackq:latest
Starting redis ... done
Starting crackq ... done
Starting nginx  ... done
Attaching to redis, crackq, nginx
redis     | 1:C 07 Dec 2023 14:54:57.564 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis     | 1:C 07 Dec 2023 14:54:57.564 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis     | 1:C 07 Dec 2023 14:54:57.564 * Redis version=7.2.3, bits=64, commit=00000000, modified=0, pid=1, just started
redis     | 1:C 07 Dec 2023 14:54:57.564 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis     | 1:M 07 Dec 2023 14:54:57.564 * monotonic clock: POSIX clock_gettime
redis     | 1:M 07 Dec 2023 14:54:57.565 * Running mode=standalone, port=6379.
redis     | 1:M 07 Dec 2023 14:54:57.566 * Server initialized
redis     | 1:M 07 Dec 2023 14:54:57.566 * Loading RDB produced by version 7.2.3
redis     | 1:M 07 Dec 2023 14:54:57.566 * RDB age 211 seconds
redis     | 1:M 07 Dec 2023 14:54:57.566 * RDB memory usage when created 0.83 Mb
redis     | 1:M 07 Dec 2023 14:54:57.566 * Done loading RDB, keys loaded: 0, keys expired: 0.
redis     | 1:M 07 Dec 2023 14:54:57.566 * DB loaded from disk: 0.000 seconds
redis     | 1:M 07 Dec 2023 14:54:57.566 * Ready to accept connections tcp
crackq    | Processing /opt/crackq/build
crackq    |   Preparing metadata (setup.py) ... done
crackq    | Building wheels for collected packages: crackq
crackq    |   Building wheel for crackq (setup.py) ... done
crackq    |   Created wheel for crackq: filename=crackq-0.1.0-py3-none-any.whl size=38858 sha256=f9021f46111fb6f76493bd337b0e5c647641ebdb17f228b55595024bb0c0005d
crackq    |   Stored in directory: /tmp/pip-ephem-wheel-cache-tql01q8z/wheels/ad/45/07/34e69083a16bf36cd3c7ab183548cbf1d5f035b166b1c0fdb5
crackq    | Successfully built crackq
crackq    | Installing collected packages: crackq
nginx     | Starting authentication failure monitor: fail2ban.
crackq    |   WARNING: The script crackq is installed in '/home/crackq/.local/bin' which is not on PATH.
crackq    |   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
crackq    | Successfully installed crackq-0.1.0
crackq    | Traceback (most recent call last):
crackq    |   File "<string>", line 1, in <module>
crackq    |   File "/opt/crackq/build/crackq/__init__.py", line 6, in <module>
crackq    |     from flask_login import (
crackq    |   File "/usr/local/lib/python3.8/dist-packages/flask_login/__init__.py", line 12, in <module>
crackq    |     from .login_manager import LoginManager
crackq    |   File "/usr/local/lib/python3.8/dist-packages/flask_login/login_manager.py", line 33, in <module>
crackq    |     from .utils import _create_identifier
crackq    |   File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 14, in <module>
crackq    |     from werkzeug.urls import url_decode
crackq    | ImportError: cannot import name 'url_decode' from 'werkzeug.urls' (/usr/local/lib/python3.8/dist-packages/werkzeug/urls.py)
crackq exited with code 1`

**Comment by f0cker** [comment]
Thanks for reporting this, Flask-Login needs updating to 0.6.3 to fix. I'll push an update soon.
