### ISSUE TITLE
Could not select device driver "nvidia" with capabilities: [[gpu]]

### ISSUE THREAD

**Issue by palulabrasil** [f0cker/crackq#45]
At the moment I finish the "NGINX Configuration" section of the guide and am able to execute the `sudo docker compose -f docker-compose.nvidia.yml up --build` command, everything runs smoothly and I can see all the steps of the docker compose process running.

In the build process these check boxes were ticked:

Network crackq_crackq_net Created;
Container redis Created;
Container crackq Created;
Container nginx Created.

However, at the end of the process this message appears:

`Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]`

However I do not know why the problem is occurring and can assure the machine is equipped with a Nvidia card as shown by executing command `nvidia-smi`:

```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.171.04             Driver Version: 535.171.04   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce 940MX           Off | 00000000:01:00.0 Off |                  N/A |
| N/A   39C    P8              N/A / 200W |      4MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1988      G   /usr/lib/xorg/Xorg                            2MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by f0cker** [comment]
Did you install the Nvidia runtime container toolkit?

Check if you can see the GPU card/s inside the container:
sudo docker run -it nvidia-ubuntu nvidia-smi

What versions do you have for Docker/Compose, Nvidia runtime, Nvidia driver, OS & CrackQ?

**Comment by f0cker** [comment]
Is this working OK for you now? Assuming it's all good and closing the issue, reopen it if not.

**Comment by palulabrasil** [comment]
Sorry @f0cker but I have been assigned to another project.
As soon as I finish this intermediate task I will return to the previous one and will disclose my findings.
Thank you.
