### ISSUE TITLE
"Error generating report: undefined"

### ISSUE THREAD

**Issue by TheTechromancer** [f0cker/crackq#5]
I'm getting an error when attempting to generate a report from a completed job.  Below is a screenshot as well as `/var/crackq/logs/crackq.log` at the time of the error.

![image](https://user-images.githubusercontent.com/20261699/70480292-5969ed00-1aad-11ea-811b-4dabb7c96def.png)

Everything else works great - hashes crack properly, etc. 

Thanks!

**Comment by f0cker** [comment]
Can you enable dev tools in the browser and check what response is coming from the API in the network tab? It might not be displaying the error properly in the GUI. There's a minimum requirement of 100 cracked passwords for report generation, how many are cracked in that job?

**Comment by TheTechromancer** [comment]
Ah okay, that turned out to be it.  There were less than 100 cracked for that job.  What are your thoughts on displaying a warning message but still allowing the report to be generated?

![image](https://user-images.githubusercontent.com/20261699/70545604-d8a60200-1b3b-11ea-8f9e-5dbe1e995b68.png)

**Comment by f0cker** [comment]
OK I can add it as an option in the conf file. For now though, you just need to edit this line:
https://github.com/f0cker/crackq/blob/0c875c0a10a334280c9e8a25649a33ccf813fa25/crackq/cq_api.py#L1415

I'll add it to the roadmap and close off this issue.
