### ISSUE TITLE
Char masks for brute force

### ISSUE THREAD

**Issue by jllang763** [f0cker/crackq#9]
Looking at the help the following are char mask that can be used
`?1 = ?l?d, ?2 = ?l?d?u, ?3 = ?l?d?s` but I am looking for a mask for `?l?u?d?s`
Is there a way to define other masks?

**Comment by f0cker** [comment]
Custom masks is something I'm going to add in future releases, but for now you can use ?a for the above requirement. If you need to a custom mask id urgently though, its here:
https://github.com/f0cker/crackq/blob/master/crackq/run_hashcat.py#L142

so you should be able to just add:
hc.custom_charset_4 = '?l?d?uxxx'

**Comment by jllang763** [comment]
Thank you.
